In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout


In [4]:
spam = pd.read_csv("spam.csv")
spam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(spam['Category'])
print(y)

[0 0 1 ... 0 0 0]


In [6]:
mensagens = spam['Message'].values
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)
print(X_train)

['You didnt complete your gist oh.'
 "Any chance you might have had with me evaporated as soon as you violated my privacy by stealing my phone number from your employer's paperwork. Not cool at all. Please do not contact me again or I will report you to your supervisor."
 'Thanx 4 2day! U r a goodmate I THINK UR RITE SARY! ASUSUAL!1 U CHEERED ME UP! LOVE U FRANYxxxxx'
 ...
 "U don't know how stubborn I am. I didn't even want to go to the hospital. I kept telling Mark I'm not a weak sucker. Hospitals are for weak suckers."
 'Thinkin about someone is all good. No drugs for that'
 'Reminder: You have not downloaded the content you have already paid for. Goto http://doit. mymoby. tv/ to collect your content.']


In [7]:
vetorizador = CountVectorizer()
vetorizador.fit(X_train)
X_train = vetorizador.transform(X_train)
X_test = vetorizador.transform(X_test)
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [9]:
X_train.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [10]:
modelo = Sequential()
modelo.add(Dense(units=10,activation="relu",input_dim=X_train.shape[1]))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=8,activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1,activation="sigmoid"))

In [11]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                72440     
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dropout_1 (Dropout)         (None, 8)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 72,537
Trainable params: 72,537
Non-trainable params: 0
_________________________________________________________________


In [13]:
modelo.fit(X_train, y_train, epochs=20, batch_size=10, verbose=True, validation_data=(X_test, y_test))

Epoch 1/20
390/390 [==============================] - 5s 6ms/step - loss: 0.0800 - accuracy: 0.9315 - val_loss: 0.0166 - val_accuracy: 0.9833
Epoch 2/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0134 - accuracy: 0.9879 - val_loss: 0.0119 - val_accuracy: 0.9874
Epoch 3/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0066 - accuracy: 0.9938 - val_loss: 0.0120 - val_accuracy: 0.9868
Epoch 4/20
390/390 [==============================] - 2s 6ms/step - loss: 0.0044 - accuracy: 0.9946 - val_loss: 0.0109 - val_accuracy: 0.9880
Epoch 5/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0029 - accuracy: 0.9967 - val_loss: 0.0110 - val_accuracy: 0.9874
Epoch 6/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0019 - accuracy: 0.9977 - val_loss: 0.0110 - val_accuracy: 0.9874
Epoch 7/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0020 - accuracy: 0.9969 - val_loss: 0.0106 - val_accuracy: 0.9874
Epoch 

In [14]:
loss, accuracy = modelo.evaluate(X_test,y_test)
print("Loss: ", loss)
print("Acurácia: ", accuracy)

53/53 [==============================] - 0s 7ms/step - loss: 0.0117 - accuracy: 0.9862
Loss:  0.011717305518686771
Acurácia:  0.9862440228462219


In [15]:
nova_previsao = modelo.predict(X_test)
print(nova_previsao)

53/53 [==============================] - 1s 3ms/step
[[7.01620406e-09]
 [2.69730988e-10]
 [1.21913792e-04]
 [6.24989438e-09]
 [4.81071856e-06]
 [1.45557463e-01]
 [9.99996603e-01]
 [1.01962993e-04]
 [1.72542987e-05]
 [8.17633641e-04]
 [8.45194192e-10]
 [2.14231580e-21]
 [3.06979893e-03]
 [1.82245632e-08]
 [1.70353303e-06]
 [2.25481126e-05]
 [1.80584502e-05]
 [5.09986023e-07]
 [9.75183735e-04]
 [2.62494796e-05]
 [2.20554764e-03]
 [5.59019918e-06]
 [4.48614854e-04]
 [9.99999344e-01]
 [5.87773451e-04]
 [1.08811691e-04]
 [1.85737022e-07]
 [9.99999404e-01]
 [1.32815214e-03]
 [8.50420183e-05]
 [6.25350440e-05]
 [1.30667510e-09]
 [2.22677591e-06]
 [9.40441714e-06]
 [2.97266437e-04]
 [9.98565316e-01]
 [1.21632820e-05]
 [2.21183973e-06]
 [9.01871972e-05]
 [6.40531312e-07]
 [7.91778293e-05]
 [1.56376103e-04]
 [1.01094216e-03]
 [2.52345903e-03]
 [3.50338183e-02]
 [2.02103074e-05]
 [1.58000663e-02]
 [1.28368483e-05]
 [7.19984819e-05]
 [4.64096075e-07]
 [2.23899775e-07]
 [4.69144812e-09]
 [6.9007702

In [16]:
prev = (nova_previsao > 0.5)
print(prev)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 

In [17]:
cm = confusion_matrix(y_test, prev)
print(cm)

[[1456    6]
 [  17  193]]
